django_kornilov/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("project-debug/", include(debug_toolbar.urls)),
    path("", include("students.urls")),
    path("", include("group.urls")),
    path("", include("teachers.urls")),
    path("", include("mail_processing.urls")),
    path("", include("currency.urls")),
    path("accounts/", include("user_signup.urls")),
]
handler404 = "students.views.handler404"
handler500 = "students.views.handler500"


admin.site.index_title = "Django Kornilov"
admin.site.site_header = "Django Kornilov Admin"
admin.site.site_title = "Admin panel"

group/urls.py
from django.urls import path

from .import views

urlpatterns = [
    path('all-groups/', views.GroupListView.as_view(), name='all-groups'),
    path('create-group/', views.CreateGroupView.as_view()),
]

students/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.MainPage.as_view(), name='main-page'),
    path('create-student/', views.CreateStudentView.as_view(), name='create-student'),
    path('generate-students/', views.GenerateStudentsView.as_view()),
    path('all-students/', views.StudentsListView.as_view(), name='all-students'),
    path('edit-student/<int:pk>/', views.EditStudentView.as_view(), name='edit-student'),
    path('delete-student/<int:pk>/', views.DeleteStudentView.as_view(), name='delete-student'),
    path('generate-students-form/', views.GenerateStudentsFormView.as_view(), name='generate-students-form')
]

students/models.py
from django.db import models


class Student(models.Model):
    first_name = models.CharField('First_name', max_length=200, db_column='First name')
    last_name = models.CharField('Last_name', max_length=200, db_column='Last name')
    age = models.IntegerField('Age', db_column='Age')
    phone_number = models.CharField(null=True, blank=True, unique=True, max_length=12, db_column='Phone number')

    in_group = models.ForeignKey("group.Group", null=True, on_delete=models.CASCADE,
                                 db_column="Group ID", verbose_name='Group ID')

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f'First name: {self.first_name}, ' \
               f'Last name: {self.last_name}, ' \
               f'Age: {self.age}, ' \
               f'Phone: {self.phone_number}'


class Logger(models.Model):
    method = models.CharField(max_length=10)
    path = models.CharField(max_length=200)
    execution_time = models.FloatField(null=False)
    created = models.DateTimeField(auto_now_add=True)

students/forms.py
import re

from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MaxValueValidator, MinValueValidator

from .models import Student


def validate_phone_number(form_phone_number):
    if not re.match(r"^380\d{9}$", form_phone_number):
        raise ValidationError(f'{form_phone_number}: Enter phone number in 380xxxxxxxxx format')


class StudentForm(forms.ModelForm):
    phone_number = forms.CharField(label='Student\'s phone', required=False,
                                   empty_value=None, validators=[validate_phone_number],
                                   widget=forms.TextInput(attrs={'placeholder': '380xxxxxxxxx'}))

    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'age', 'phone_number']


class GenerateStudentsForm(forms.Form):
    total = forms.IntegerField(
        validators=[
            MinValueValidator(10),
            MaxValueValidator(500)
        ]
    )

students/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, View
from django.views.generic.edit import CreateView, DeleteView, FormView, UpdateView

from faker import Faker

from .forms import GenerateStudentsForm, StudentForm
from .models import Student
from .tasks import generate_random_students


class MainPage(View):
    def get(self, request):
        return render(request, 'students/index.html')


class CreateStudentView(LoginRequiredMixin, CreateView):
    form_class = StudentForm
    template_name = 'students/create_student_form.html'

    def form_valid(self, form):
        Student.objects.create(**form.cleaned_data)
        return redirect('all-students')


class GenerateStudentsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        fake = Faker()
        count = self.request.GET.get('count', '0')
        if count.isnumeric() and 0 < int(count) <= 100:
            students_result = []
            for i in range(1, int(count) + 1):
                students_result.append(Student(first_name=fake.first_name(),
                                               last_name=fake.last_name(),
                                               age=fake.random_int(18, 26)))
            Student.objects.bulk_create(students_result)
            return redirect('all-students')
        elif count == '0':
            return HttpResponse('<h1>Default value is 0</h1>'
                                '<br>Enter positive number from 1 too 100')
        else:
            return HttpResponse('<h3>Enter positive number from 1 too 100</h3>')


class EditStudentView(LoginRequiredMixin, UpdateView):
    model = Student
    template_name = 'students/student_edit_form.html'
    form_class = StudentForm
    success_url = reverse_lazy('all-students')


class DeleteStudentView(LoginRequiredMixin, DeleteView):
    model = Student
    success_url = reverse_lazy('all-students')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)


class StudentsListView(ListView):
    model = Student
    template_name = 'students/students_list.html'
    paginate_by = 20

    def get_queryset(self):
        filter_params = {}
        student_id = self.request.GET.get('id', '')
        if student_id:
            filter_params['id'] = student_id

        student_first_name = self.request.GET.get('first_name', '')
        if student_first_name:
            filter_params['first_name'] = student_first_name

        student_last_name = self.request.GET.get('last_name', '')
        if student_last_name:
            filter_params['last_name'] = student_last_name

        student_age = self.request.GET.get('age', '')
        if student_age:
            filter_params['age'] = student_age

        queryset = Student.objects.filter(**filter_params)
        return queryset


class GenerateStudentsFormView(LoginRequiredMixin, FormView):
    template_name = 'students/student_generator.html'
    form_class = GenerateStudentsForm

    def form_valid(self, form):
        total = form.cleaned_data.get('total')
        generate_random_students.delay(total)
        messages.success(self.request, 'We are generating random students! Wait a moment and refresh this page.')
        return redirect('all-students')


def handler404(request, exception):
    return render(request, './errors/404_error_handler.html', status=404)


def handler500(request):
    return render(request, './errors/404_error_handler.html', status=500)

students/templates/students/create_student_form.html
{% extends "base.html" %}
{% block head %}
    <title>Student creation form</title>
    {{ block.super }}
{% endblock %}
{% block content %}
    <h1>Student creation form</h1>
    <form action="/create-student/" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

students/templates/students/index.html
{% extends "base.html" %}

{% block content %}
    <h2><a href="/admin" style="color: black">Admin</a></h2>
    <h2><a href="{% url 'create-student' %}" style="color: black">Create student</a></h2>
    <h2><a href="{% url 'all-students' %}" style="color: black">Show all students</a></h2>
    <h2><a href="{% url 'create-teacher' %}" style="color: black">Create teacher</a></h2>
    <h2><a href="{% url 'all-teachers' %}" style="color: black">Show all teachers</a></h2>
    <h2><a href="{% url 'all-groups' %}" style="color: black">Show all groups</a></h2>
    <h2><a href="{% url 'contact-us' %}" style="color: black">Contact Us</a></h2>
    <h2><a href="{% url 'currency-list' %}" style="color: black">Currency list</a></h2>
    {% if user.is_authenticated %}
        Hello, {{ user.username }}!
        <br/>
        <br/>
        <h4><a href="{% url 'logout' %}" style="color: darkslategray">Log Out</a></h4>
        <h4><a href="{% url 'password_change' %}" style="color: darkslategray">Change your password</a></h4>
    {% else %}
        <h4>You are not logged in</h4>
        <br/>
        <h4 style="color: wheat"><a href="{% url 'login' %}" style="color: darkseagreen">Log In</a> |
            <a href="{% url 'signup' %}" style="color: darkseagreen">SignUp</a> |
            <a href="{% url 'password_reset' %}" style="color: darkseagreen">Forgot your password?</a></h4>
    {% endif %}
{% endblock %}

students/templates/students/student_edit_form.html
{% extends "base.html" %}
{% block head %}
    <title>Edit student</title>
    {{ block.super }}
{% endblock %}
{% block content %}
    <h1>Student edit form</h1>
    <form action="{% url 'edit-student' object.pk %}" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

students/templates/students/student_generator.html
{% extends "base.html" %}

{% block content %}
    <h1>Random student generation form</h1>
    <form action="{% url 'generate-students-form' %}" method="post">
        {% csrf_token %}
        <table>
            {{form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

students/templates/students/students_list.html
{% extends "base.html" %}

{% block head %}
    <title>All Students</title>
    {{ block.super }}
{% endblock %}
{% block content %}
    <table>
        <th>ID</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Age</th>
        <th>Phone number</th>
        <th>Group ID</th>
        <th>Group name</th>
        <th>Edit data</th>
        <th>Delete from base</th>
        {% for student in student_list %}
            <tr>
                <td>{{ student.id|safe }}</td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.age }}</td>
                <td>{{ student.phone_number }}</td>
                <td>{{ student.in_group.id }}</td>
                <td>{{ student.in_group.group_name }}</td>
                <td>
                    <a href="{% url 'edit-student' student.id %}">
                        <button class="button button1">Edit</button>
                    </a>
                </td>
                <td>
                    <a href="{% url 'delete-student' student.id %}">
                        <button class="button button2">Delete</button>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table
{% endblock %}