django_kornilov/urls.py
import debug_toolbar

from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    path("project-debug/", include(debug_toolbar.urls)),
    path("", include("students.urls")),
    path("", include("group.urls")),
    path("", include("teachers.urls")),
    path("", include("mail_processing.urls")),
    path("", include("currency.urls")),
    path("accounts/", include("user_signup.urls")),
]
handler404 = "students.views.handler404"
handler500 = "students.views.handler500"


admin.site.index_title = "Django Kornilov"
admin.site.site_header = "Django Kornilov Admin"
admin.site.site_title = "Admin panel"

group/urls.py
from django.urls import path

from .import views

urlpatterns = [
    path('all-groups/', views.GroupListView.as_view(), name='all-groups'),
    path('create-group/', views.CreateGroupView.as_view()),
]

teachers/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('all-teachers/', views.TeachersListView.as_view(), name='all-teachers'),
    path('create-teacher/', views.CreateTeacherView.as_view(), name='create-teacher'),
    path('edit-teacher/<int:pk>/', views.EditTeacherView.as_view(), name='edit-teacher'),
    path('delete-teacher/<int:pk>/', views.DeleteTeacherView.as_view(), name='delete-teacher'),
]

teachers/models.py
from django.db import models


class Teacher(models.Model):
    subject = models.CharField('Subject', max_length=200, db_column='Subject')
    first_name = models.CharField('First name', max_length=200, db_column='First name')
    last_name = models.CharField('Last name', max_length=200, db_column='Last name')
    age = models.IntegerField('Age', db_column='Age')

    class Meta:
        ordering = ['id']

    def __str__(self):
        return f'ID: {self.id}, '\
               f'Subject: {self.subject}, ' \
               f'First name: {self.first_name}, ' \
               f'Last name: {self.last_name}, ' \
               f'Age: {self.age}'

teachers/forms.py
from django import forms

from .models import Teacher


class TeacherForm(forms.ModelForm):
    subject = forms.CharField(label='Subject', required=True, max_length=200)
    first_name = forms.CharField(label='First name', required=True, max_length=200)
    last_name = forms.CharField(label='Last name', required=True, max_length=200)
    age = forms.IntegerField(label='Age')

    class Meta:
        model = Teacher
        fields = ['subject', 'first_name', 'last_name', 'age']

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView


from .forms import TeacherForm
from .models import Teacher


class CreateTeacherView(LoginRequiredMixin, CreateView):
    form_class = TeacherForm
    template_name = 'teachers/create_teacher_form.html'

    def form_valid(self, form):
        Teacher.objects.create(**form.cleaned_data)
        return redirect('all-teachers')


class EditTeacherView(LoginRequiredMixin, UpdateView):
    model = Teacher
    template_name = 'teachers/teacher_edit_form.html'
    form_class = TeacherForm
    success_url = reverse_lazy('all-teachers')


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    model = Teacher
    success_url = reverse_lazy('all-teachers')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)


class TeachersListView(ListView):
    model = Teacher
    template_name = 'teachers/teachers_list.html'
    paginate_by = 20

    def get_queryset(self):
        filter_params = {}
        teacher_id = self.request.GET.get('id', '')
        if teacher_id:
            filter_params['id'] = teacher_id
        teacher_first_name = self.request.GET.get('first_name', '')
        if teacher_first_name:
            filter_params['first_name'] = teacher_first_name
        teacher_last_name = self.request.GET.get('last_name', '')
        if teacher_last_name:
            filter_params['last_name'] = teacher_last_name
        teacher_age = self.request.GET.get('age', '')
        if teacher_age:
            filter_params['age'] = teacher_age
        queryset = Teacher.objects.filter(**filter_params)
        return queryset

teachers/templates/teachers/create_teacher_form.html
{% extends "base.html" %}
{% block head %}
    <title>Teacher creation form</title>
    {{ block.super }}
    <style type="text/css">
        body {
            background-color: darksalmon;
        }
    </style>
{% endblock %}
{% block content %}
    <h1>Teacher creation form</h1>
    <form action="/create-teacher/" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

teachers/templates/teachers/teacher_edit_form.html
{% extends "base.html" %}
{% block head %}
    <title>Edit teacher</title>
    {{ block.super }}
    <style type="text/css">
        body {
            background-color: darksalmon;
        }
    </style>
{% endblock %}
{% block content %}
    <h1>Teacher edit form</h1>
    <form action="{% url 'edit-teacher' object.pk %}" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

teachers/templates/teachers/teachers_list.html
{% extends "base.html" %}
{% block head %}
    <title>All Teachers</title>
    {{ block.super }}
    <style type="text/css">
        body {
            background-color: darksalmon;
        }
        .button1 {
            border: 2px solid darksalmon;
        }

        .button1:hover {
            background-color: darksalmon;
        }

    </style>
{% endblock %}

{% block content %}
    <table>
        <th>ID</th>
        <th>Subject</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Age</th>
        <th>Edit data</th>
        <th>Delete from base</th>
        {% for teacher in teacher_list %}
            <tr>
                <td>{{ teacher.id|safe }}</td>
                <td>{{ teacher.subject }}</td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.age }}</td>
                <td>
                    <a href="{% url 'edit-teacher' teacher.id %}">
                        <button class="button button1 ">Edit</button>
                    </a>
                </td>
                <td>
                    <a href="{% url 'delete-teacher' teacher.id %}">
                        <button class="button button2">Delete</button>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}